# docker-compose.yml
version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'app_ccymc'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
  celery:
    build: .
    container_name: 'app_celery'
    command: celery -A ccymc beat -B
    command: celery -A ccymc worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis