# Generated by Django 3.2.5 on 2021-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_coin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='name',
            new_name='base',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='image',
        ),
        migrations.AddField(
            model_name='coin',
            name='target',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
